root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main.exe ./cmd/notifyhub/main.go"
  bin = "./tmp/main.exe"
  include_ext = ["go", "tpl", "tmpl", "html", "proto"]
  exclude_dir = ["bin", "tmp", "vendor"]
  delay = 1000
  stop_on_error = true

[log]
  time = true