version: '3.8'

services:
  notify-hub:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./configs:/root/configs
    environment:
      - LOG_LEVEL=info
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped